"""empty message

Revision ID: 79219147aba6
Revises: 5b7eb5e40166
Create Date: 2020-01-12 02:34:04.768438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79219147aba6'
down_revision = '5b7eb5e40166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Movies', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('Movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Movies', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
